[project]
name = "gentic-phone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.3",
    "pillow>=11.0.0",
    "pollinations>=2.1",
]
